AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handles the back-end for creating and joining games in the scratchpad telephone app.
Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
  Function:
    Runtime: nodejs12.x
    CodeUri: ./
    Policies: arn:aws:iam::867596066550:policy/ScratchpadTelepGamesServicePolicy
Resources:
  ScratchpadTelepNewGameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.newGameHandler
      Policies: arn:aws:iam::867596066550:policy/ScratchpadTelepGamesServicePolicy
      Events:
        ScratchpadTelepNewGameApi:
          Type: Api
          Properties:
            Path: /games
            Method: POST
  ScratchpadTelepJoinGameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.joinGameHandler
      Events:
        Type: Api
        Properties:
          Path: /games/{token}
          Method: GET
