version: 0.2

env:
  variables:
    GIT_URL: "git@github.com:markbiddlecom/ScratchpadTelephone.git"
  parameter-store:
    SSH_KEY: github_id_rsa
    SSH_PUB: github_id_rsa_pub
    KEY_PASSPHRASE: github_id_rsa_passphrase

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli
      # Initialize our submodule
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa
      - echo "$SSH_PUB" > ~/.ssh/id_rsa.pub
      - chmod 600 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - echo "$KEY_PASSPHRASE" | ssh-add -p ~/.ssh/id_rsa
      - git init
      - git remote add origin "$GIT_URL"
      - git fetch origin
      - git branch
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - git submodule init
      - git submodule update --recursive
  pre_build:
    commands:
      # Build the canvas dependency
      - cd react-canvas-draw
      - npm install
      - npm run build
      # Install in our main project
      - cd ../web
      - npm install
  build:
    commands:
      # Produce a build
      - npm run test:nowatch
      - npm run build
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
      - cd ..
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
artifacts:
  base-directory: web/build/
  files:
    - ./**/*
